# Generated by Django 5.0.1 on 2024-01-15 14:40

from django.db import migrations
import csv

def load_data_from_csv(apps, schema_editor):
    Evenement = apps.get_model('vstrom', 'Evenement')
    Participant = apps.get_model('vstrom', 'Participant')

    # Charger les données des fichiers CSV pour les événements
    with open('vstrom/data/evenements.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            Evenement.objects.create(
                nom=row['nom'],
                date=row['date']
            )

    # Charger les données des fichiers CSV pour les participants
    with open('vstrom/data/participants.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            Participant.objects.create(
                prenom=row['prenom'],
                nom=row['nom']
            )
class Migration(migrations.Migration):

    dependencies = [
        ('vstrom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data_from_csv),
    ]
