# Generated by Django 5.0.1 on 2024-01-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstrom', '0002_auto_20240115_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image_url',
            field=models.URLField(default='http://url_a_definir'),
        ),
    ]
