# Generated by Django 5.0.1 on 2024-01-15 15:18

from django.db import migrations
import random
from vstrom.models import Evenement, Participant, Participation


"""
Création d'associations fictives entres les participants et les évènements
pour utiliser un jeu de données minimal.
"""
def generate_random_participations(apps, schema_editor):
    evenements = Evenement.objects.all()
    participants = list(Participant.objects.all()) #conversion en liste pour pouvoir faire un random.shuffle (sinon erreur de QuerySet)

    for evenement in evenements:
        # Choisissez un nombre aléatoire de participants pour chaque événement
        nombre_participants = random.randint(1, len(participants))

        # Mélangez la liste des participants
        random.shuffle(participants)

        # Sélectionnez les participants en fonction du nombre aléatoire
        participants_evenement = participants[:nombre_participants]

        # Créez des participations pour chaque participant sélectionné
        for participant in participants_evenement:
            Participation.objects.create(
                evenement=evenement,
                participant=participant
            )
class Migration(migrations.Migration):

    dependencies = [
        ('vstrom', '0003_evenement_image_url'),
    ]

    operations = [
        migrations.RunPython(generate_random_participations),
    ]
