# Generated by Django 5.0.1 on 2024-01-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstrom', '0003_evenement_image_url'),
    ]

    operations = [
    ]
